=== swmud-net/swaedit/schemas/exits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://swmud.pl/ns/swaedit/exits"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://swmud.pl/ns/swaedit/exits"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="1.0">

	<xsd:annotation>
		<xsd:appinfo>
			<jxb:globalBindings collectionType="java.util.LinkedList" />
		</xsd:appinfo>
	</xsd:annotation>

	<xsd:element name="exits" type="exits"></xsd:element>

	<xsd:complexType name="exit">
		<xsd:sequence maxOccurs="1" minOccurs="0">
			<xsd:element name="abbreviation"
				type="xsd:normalizedString">
			</xsd:element>
			<xsd:element name="name" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="value" type="xsd:unsignedByte"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="empty" type="xsd:boolean" use="optional"
			default="false">
		</xsd:attribute>
		<xsd:attribute name="opposite" type="xsd:byte" use="optional" default="-1"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="exits">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="exit" type="exit"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="gridColumns" type="xsd:unsignedByte"
			use="optional" default="3">
		</xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== swmud-net/swaedit/data/exits.xml
<?xml version="1.0" encoding="UTF-8"?>
<exits xmlns="http://swmud.pl/ns/swaedit/exits"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/exits src/exits.xsd ">
	<exit opposite="8">
		<abbreviation>NW</abbreviation>
		<name>north-west</name>
		<value>7</value>
	</exit>

	<exit opposite="2">
		<abbreviation>N</abbreviation>
		<name>north</name>
		<value>0</value>
	</exit>

	<exit opposite="9">
		<abbreviation>NE</abbreviation>
		<name>north-east</name>
		<value>6</value>
	</exit>

	<exit opposite="1">
		<abbreviation>W</abbreviation>
		<name>west</name>
		<value>3</value>
	</exit>

	<exit>
		<abbreviation>?</abbreviation>
		<name>somewhere</name>
		<value>10</value>
	</exit>

	<exit opposite="3">
		<abbreviation>E</abbreviation>
		<name>east</name>
		<value>1</value>
	</exit>

	<exit opposite="6">
		<abbreviation>SW</abbreviation>
		<name>south-west</name>
		<value>9</value>
	</exit>

	<exit opposite="0">
		<abbreviation>S</abbreviation>
		<name>south</name>
		<value>2</value>
	</exit>

	<exit opposite="7">
		<abbreviation>SE</abbreviation>
		<name>south-east</name>
		<value>8</value>
	</exit>

	<exit opposite="5">
		<abbreviation>Up</abbreviation>
		<name>up</name>
		<value>4</value>
	</exit>

	<exit opposite="4">
		<abbreviation>Dn</abbreviation>
		<name>down</name>
		<value>5</value>
	</exit>
</exits>
