=== swmud-net/swaedit/schemas/flags.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://swmud.pl/ns/swaedit/flags"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="1.0">

	<xsd:annotation>
		<xsd:appinfo>
			<jxb:globalBindings collectionType="java.util.LinkedList"/>
		</xsd:appinfo>
	</xsd:annotation>

	<xsd:element name="flags" type="flags"></xsd:element>

	<xsd:complexType name="flags">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="flag" type="flag"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="flag">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="value" type="xsd:integer"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== swmud-net/swaedit/data/itemwearflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
		<name>take</name>
		<value>1</value>
	</flag>
	<flag>
		<name>finger</name>
		<value>2</value>
	</flag>
	<flag>
		<name>neck</name>
		<value>4</value>
	</flag>
	<flag>
		<name>body</name>
		<value>8</value>
	</flag>
	<flag>
		<name>head</name>
		<value>16</value>
	</flag>
	<flag>
		<name>legs</name>
		<value>32</value>
	</flag>
	<flag>
		<name>feet</name>
		<value>64</value>
	</flag>
	<flag>
		<name>hands</name>
		<value>128</value>
	</flag>
	<flag>
		<name>arms</name>
		<value>256</value>
	</flag>
	<flag>
		<name>shield</name>
		<value>512</value>
	</flag>
	<flag>
		<name>about</name>
		<value>1024</value>
	</flag>
	<flag>
		<name>waist</name>
		<value>2048</value>
	</flag>
	<flag>
		<name>wrist</name>
		<value>4096</value>
	</flag>
	<flag>
		<name>wield</name>
		<value>8192</value>
	</flag>
	<flag>
		<name>hold</name>
		<value>16384</value>
	</flag>
	<flag>
		<name>dual_wield</name>
		<value>32768</value>
	</flag>
	<flag>
		<name>ears</name>
		<value>65536</value>
	</flag>
	<flag>
		<name>eyes</name>
		<value>131072</value>
	</flag>
	<flag>
		<name>missile_wield</name>
		<value>262144</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/resistflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
	    <name>fire</name>
	    <value>1</value>
	</flag>
	<flag>
	    <name>cold</name>
	    <value>2</value>
	</flag>
	<flag>
	    <name>electricity</name>
	    <value>4</value>
	</flag>
	<flag>
	    <name>energy</name>
	    <value>8</value>
	</flag>
	<flag>
	    <name>blunt</name>
	    <value>16</value>
	</flag>
	<flag>
	    <name>pierce</name>
	    <value>32</value>
	</flag>
	<flag>
	    <name>slash</name>
	    <value>64</value>
	</flag>
	<flag>
	    <name>acid</name>
	    <value>128</value>
	</flag>
	<flag>
	    <name>poison</name>
	    <value>256</value>
	</flag>
	<flag>
	    <name>drain</name>
	    <value>512</value>
	</flag>
	<flag>
	    <name>sleep</name>
	    <value>1024</value>
	</flag>
	<flag>
	    <name>charm</name>
	    <value>2048</value>
	</flag>
	<flag>
	    <name>hold</name>
	    <value>4096</value>
	</flag>
	<flag>
	    <name>nonforce</name>
	    <value>8192</value>
	</flag>
	<flag>
	    <name>plus1</name>
	    <value>16384</value>
	</flag>
	<flag>
	    <name>plus2</name>
	    <value>32768</value>
	</flag>
	<flag>
	    <name>plus3</name>
	    <value>65536</value>
	</flag>
	<flag>
	    <name>plus4</name>
	    <value>131072</value>
	</flag>
	<flag>
	    <name>plus5</name>
	    <value>262144</value>
	</flag>
	<flag>
	    <name>plus6</name>
	    <value>524288</value>
	</flag>
	<flag>
	    <name>force</name>
	    <value>1048576</value>
	</flag>
	<flag>
	    <name>paralysis</name>
	    <value>2097152</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/defenseflags.xml
<?xml version="1.0" encoding="UTF-8"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
	    <name>parry</name>
	    <value>1</value>
	</flag>
	<flag>
	    <name>dodge</name>
	    <value>2</value>
	</flag>
	<flag>
	    <name>heal</name>
	    <value>4</value>
	</flag>
	<flag>
	    <name>curelight</name>
	    <value>8</value>
	</flag>
	<flag>
	    <name>cureserious</name>
	    <value>16</value>
	</flag>
	<flag>
	    <name>curecritical</name>
	    <value>32</value>
	</flag>
	<flag>
	    <name>dispelforce</name>
	    <value>64</value>
	</flag>
	<flag>
	    <name>dispelevil</name>
	    <value>128</value>
	</flag>
	<flag>
	    <name>sanctuary</name>
	    <value>256</value>
	</flag>
	<flag>
	    <name>fireshield</name>
	    <value>512</value>
	</flag>
	<flag>
	    <name>shockshield</name>
	    <value>1024</value>
	</flag>
	<flag>
	    <name>shield</name>
	    <value>2048</value>
	</flag>
	<flag>
	    <name>bless</name>
	    <value>4096</value>
	</flag>
	<flag>
	    <name>stoneskin</name>
	    <value>8192</value>
	</flag>
	<flag>
	    <name>teleport</name>
	    <value>16384</value>
	</flag>
	<flag>
	    <name>monsum1</name>
	    <value>32768</value>
	</flag>
	<flag>
	    <name>monsum2</name>
	    <value>65536</value>
	</flag>
	<flag>
	    <name>monsum3</name>
	    <value>131072</value>
	</flag>
	<flag>
	    <name>monsum4</name>
	    <value>262144</value>
	</flag>
	<flag>
	    <name>disarm</name>
	    <value>524288</value>
	</flag>
	<flag>
	    <name>iceshield</name>
	    <value>1048576</value>
	</flag>
	<flag>
	    <name>grip</name>
	    <value>2097152</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/areaflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
		<name>nopkill</name>
		<value>1</value>
	</flag>
	<flag>
		<name>nightdesc</name>
		<value>2</value>
	</flag>
	<flag>
		<name>nohail</name>
		<value>4</value>
	</flag>
	<flag>
		<name>hidden</name>
		<value>8</value>
	</flag>
	<flag>
		<name>dont_show_planet</name>
		<value>16</value>
	</flag>
	<flag>
		<name>prototype</name>
		<value>32</value>
	</flag>
	<flag>
		<name>for_ships</name>
		<value>64</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/xflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
	    <name>head</name>
	    <value>1</value>
	</flag>
	<flag>
	    <name>arms</name>
	    <value>2</value>
	</flag>
	<flag>
	    <name>legs</name>
	    <value>4</value>
	</flag>
	<flag>
	    <name>heart</name>
	    <value>8</value>
	</flag>
	<flag>
	    <name>brains</name>
	    <value>16</value>
	</flag>
	<flag>
	    <name>guts</name>
	    <value>32</value>
	</flag>
	<flag>
	    <name>hands</name>
	    <value>64</value>
	</flag>
	<flag>
	    <name>feet</name>
	    <value>128</value>
	</flag>
	<flag>
	    <name>fingers</name>
	    <value>256</value>
	</flag>
	<flag>
	    <name>ear</name>
	    <value>512</value>
	</flag>
	<flag>
	    <name>eye</name>
	    <value>1024</value>
	</flag>
	<flag>
	    <name>long_tongue</name>
	    <value>2048</value>
	</flag>
	<flag>
	    <name>eyestalks</name>
	    <value>4096</value>
	</flag>
	<flag>
	    <name>tentacles</name>
	    <value>8192</value>
	</flag>
	<flag>
	    <name>fins</name>
	    <value>16384</value>
	</flag>
	<flag>
	    <name>wings</name>
	    <value>32768</value>
	</flag>
	<flag>
	    <name>tail</name>
	    <value>65536</value>
	</flag>
	<flag>
	    <name>leku</name>
	    <value>131072</value>
	</flag>
	<flag>
	    <name>claws</name>
	    <value>134217728</value>
	</flag>
	<flag>
	    <name>fangs</name>
	    <value>268435456</value>
	</flag>
	<flag>
	    <name>horns</name>
	    <value>536870912</value>
	</flag>
	<flag>
	    <name>scales</name>
	    <value>1073741824</value>
	</flag>
	<flag>
	    <name>tusks</name>
	    <value>2147483648</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/attackflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
	    <name>bite</name>
	    <value>1</value>
	</flag>
	<flag>
	    <name>claws</name>
	    <value>2</value>
	</flag>
	<flag>
	    <name>tail</name>
	    <value>4</value>
	</flag>
	<flag>
	    <name>sting</name>
	    <value>8</value>
	</flag>
	<flag>
	    <name>punch</name>
	    <value>16</value>
	</flag>
	<flag>
	    <name>kick</name>
	    <value>32</value>
	</flag>
	<flag>
	    <name>trip</name>
	    <value>64</value>
	</flag>
	<flag>
	    <name>bash</name>
	    <value>128</value>
	</flag>
	<flag>
	    <name>stun</name>
	    <value>256</value>
	</flag>
	<flag>
	    <name>gouge</name>
	    <value>512</value>
	</flag>
	<flag>
	    <name>backstab</name>
	    <value>1024</value>
	</flag>
	<flag>
	    <name>feed</name>
	    <value>2048</value>
	</flag>
	<flag>
	    <name>drain</name>
	    <value>4096</value>
	</flag>
	<flag>
	    <name>firebreath</name>
	    <value>8192</value>
	</flag>
	<flag>
	    <name>frostbreath</name>
	    <value>16384</value>
	</flag>
	<flag>
	    <name>acidbreath</name>
	    <value>32768</value>
	</flag>
	<flag>
	    <name>lightnbreath</name>
	    <value>65536</value>
	</flag>
	<flag>
	    <name>gasbreath</name>
	    <value>131072</value>
	</flag>
	<flag>
	    <name>poison</name>
	    <value>262144</value>
	</flag>
	<flag>
	    <name>nastypoison</name>
	    <value>524288</value>
	</flag>
	<flag>
	    <name>gaze</name>
	    <value>1048576</value>
	</flag>
	<flag>
	    <name>blindness</name>
	    <value>2097152</value>
	</flag>
	<flag>
	    <name>causeserious</name>
	    <value>4194304</value>
	</flag>
	<flag>
	    <name>earthquake</name>
	    <value>8388608</value>
	</flag>
	<flag>
	    <name>causecritical</name>
	    <value>16777216</value>
	</flag>
	<flag>
	    <name>curse</name>
	    <value>33554432</value>
	</flag>
	<flag>
	    <name>flamestrike</name>
	    <value>67108864</value>
	</flag>
	<flag>
	    <name>harm</name>
	    <value>134217728</value>
	</flag>
	<flag>
	    <name>fireball</name>
	    <value>268435456</value>
	</flag>
	<flag>
	    <name>colorspray</name>
	    <value>536870912</value>
	</flag>
	<flag>
	    <name>weaken</name>
	    <value>1073741824</value>
	</flag>
	<flag>
	    <name>spiralblast</name>
	    <value>2147483648</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/mobileactflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
	    <name>is_npc</name>
	    <value>1</value>
	</flag>
	<flag>
	    <name>sentinel</name>
	    <value>2</value>
	</flag>
	<flag>
	    <name>scavenger</name>
	    <value>4</value>
	</flag>
	<flag>
	    <name>aggressive</name>
	    <value>32</value>
	</flag>
	<flag>
	    <name>stay_area</name>
	    <value>64</value>
	</flag>
	<flag>
	    <name>wimpy</name>
	    <value>128</value>
	</flag>
	<flag>
	    <name>pet</name>
	    <value>256</value>
	</flag>
	<flag>
	    <name>train</name>
	    <value>512</value>
	</flag>
	<flag>
	    <name>practice</name>
	    <value>1024</value>
	</flag>
	<flag>
	    <name>immortal</name>
	    <value>2048</value>
	</flag>
	<flag>
	    <name>deadly</name>
	    <value>4096</value>
	</flag>
	<flag>
	    <name>polyself</name>
	    <value>8192</value>
	</flag>
	<flag>
	    <name>meta_aggr</name>
	    <value>16384</value>
	</flag>
	<flag>
	    <name>guardian</name>
	    <value>32768</value>
	</flag>
	<flag>
	    <name>running</name>
	    <value>65536</value>
	</flag>
	<flag>
	    <name>nowander</name>
	    <value>131072</value>
	</flag>
	<flag>
	    <name>mountable</name>
	    <value>262144</value>
	</flag>
	<flag>
	    <name>mounted</name>
	    <value>524288</value>
	</flag>
	<flag>
	    <name>scholar</name>
	    <value>1048576</value>
	</flag>
	<flag>
	    <name>secretive</name>
	    <value>2097152</value>
	</flag>
	<flag>
	    <name>polymorphed</name>
	    <value>4194304</value>
	</flag>
	<flag>
	    <name>mobinvis</name>
	    <value>8388608</value>
	</flag>
	<flag>
	    <name>noassist</name>
	    <value>16777216</value>
	</flag>
	<flag>
	    <name>nokill</name>
	    <value>33554432</value>
	</flag>
	<flag>
	    <name>droid</name>
	    <value>67108864</value>
	</flag>
	<flag>
	    <name>nocorpse</name>
	    <value>134217728</value>
	</flag>
	<flag>
	    <name>quest</name>
	    <value>268435456</value>
	</flag>
	<flag>
	    <name>prototype</name>
	    <value>1073741824</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/roomflags.xml
<?xml version="1.0" encoding="UTF-8"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
	    <name>dark</name>
	    <value>1</value>
	</flag>
	<flag>
	    <name>no_find</name>
	    <value>2</value>
	</flag>
	<flag>
	    <name>no_mob</name>
	    <value>4</value>
	</flag>
	<flag>
	    <name>indoors</name>
	    <value>8</value>
	</flag>
	<flag>
	    <name>can_land</name>
	    <value>16</value>
	</flag>
	<flag>
	    <name>can_fly</name>
	    <value>32</value>
	</flag>
	<flag>
	    <name>no_driving</name>
	    <value>64</value>
	</flag>
	<flag>
	    <name>no_force</name>
	    <value>128</value>
	</flag>
	<flag>
	    <name>bank</name>
	    <value>256</value>
	</flag>
	<flag>
	    <name>private</name>
	    <value>512</value>
	</flag>
	<flag>
	    <name>safe</name>
	    <value>1024</value>
	</flag>
	<flag>
	    <name>import</name>
	    <value>2048</value>
	</flag>
	<flag>
	    <name>pet_shop</name>
	    <value>4096</value>
	</flag>
	<flag>
	    <name>bacta</name>
	    <value>8192</value>
	</flag>
	<flag>
	    <name>donation</name>
	    <value>16384</value>
	</flag>
	<flag>
	    <name>nodropall</name>
	    <value>32768</value>
	</flag>
	<flag>
	    <name>silence</name>
	    <value>65536</value>
	</flag>
	<flag>
	    <name>logspeech</name>
	    <value>131072</value>
	</flag>
	<flag>
	    <name>nodrop</name>
	    <value>262144</value>
	</flag>
	<flag>
	    <name>stock_market</name>
	    <value>524288</value>
	</flag>
	<flag>
	    <name>plr_home</name>
	    <value>1048576</value>
	</flag>
	<flag>
	    <name>empty_home</name>
	    <value>2097152</value>
	</flag>
	<flag>
	    <name>teleport</name>
	    <value>4194304</value>
	</flag>
	<flag>
	    <name>hotel</name>
	    <value>8388608</value>
	</flag>
	<flag>
	    <name>nofloor</name>
	    <value>16777216</value>
	</flag>
	<flag>
	    <name>refinery</name>
	    <value>33554432</value>
	</flag>
	<flag>
	    <name>factory</name>
	    <value>67108864</value>
	</flag>
	<flag>
	    <name>killarena</name>
	    <value>134217728</value>
	</flag>
	<flag>
	    <name>safearena</name>
	    <value>268435456</value>
	</flag>
	<flag>
	    <name>spacecraft</name>
	    <value>536870912</value>
	</flag>
	<flag>
	    <name>prototype</name>
	    <value>1073741824</value>
	</flag>
	<flag>
	    <name>auction</name>
	    <value>2147483648</value>
	</flag>
</flags>
