=== swmud-net/swaedit/schemas/flags.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://swmud.pl/ns/swaedit/flags"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="1.0">

	<xsd:annotation>
		<xsd:appinfo>
			<jxb:globalBindings collectionType="java.util.LinkedList"/>
		</xsd:appinfo>
	</xsd:annotation>

	<xsd:element name="flags" type="flags"></xsd:element>

	<xsd:complexType name="flags">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="flag" type="flag"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="flag">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="value" type="xsd:integer"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== swmud-net/swaedit/data/exitflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
	    <name>isdoor</name>
	    <value>1</value>
	</flag>
	<flag>
	    <name>closed</name>
	    <value>2</value>
	</flag>
	<flag>
	    <name>locked</name>
	    <value>4</value>
	</flag>
	<flag>
	    <name>secret</name>
	    <value>8</value>
	</flag>
	<flag>
	    <name>swim</name>
	    <value>16</value>
	</flag>
	<flag>
	    <name>pickproof</name>
	    <value>32</value>
	</flag>
	<flag>
	    <name>fly</name>
	    <value>64</value>
	</flag>
	<flag>
	    <name>climb</name>
	    <value>128</value>
	</flag>
	<flag>
	    <name>dig</name>
	    <value>256</value>
	</flag>
	<flag>
	    <name>res1</name>
	    <value>512</value>
	</flag>
	<flag>
	    <name>nopassdoor</name>
	    <value>1024</value>
	</flag>
	<flag>
	    <name>hidden</name>
	    <value>2048</value>
	</flag>
	<flag>
	    <name>passage</name>
	    <value>4096</value>
	</flag>
	<flag>
	    <name>portal</name>
	    <value>8192</value>
	</flag>
	<flag>
	    <name>res2</name>
	    <value>16384</value>
	</flag>
	<flag>
	    <name>res3</name>
	    <value>32768</value>
	</flag>
	<flag>
	    <name>xclimb</name>
	    <value>65536</value>
	</flag>
	<flag>
	    <name>xenter</name>
	    <value>131072</value>
	</flag>
	<flag>
	    <name>xleave</name>
	    <value>262144</value>
	</flag>
	<flag>
	    <name>xauto</name>
	    <value>524288</value>
	</flag>
	<flag>
	    <name>res4</name>
	    <value>1048576</value>
	</flag>
	<flag>
	    <name>xsearchable</name>
	    <value>2097152</value>
	</flag>
	<flag>
	    <name>bashed</name>
	    <value>4194304</value>
	</flag>
	<flag>
	    <name>bashproof</name>
	    <value>8388608</value>
	</flag>
	<flag>
	    <name>nomob</name>
	    <value>16777216</value>
	</flag>
	<flag>
	    <name>window</name>
	    <value>33554432</value>
	</flag>
	<flag>
	    <name>xlook</name>
	    <value>67108864</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/itemextraflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
		<name>glow</name>
		<value>1</value>
	</flag>
	<flag>
		<name>hum</name>
		<value>2</value>
	</flag>
	<flag>
		<name>quest</name>
		<value>4</value>
	</flag>
	<flag>
		<name>hutt_size</name>
		<value>8</value>
	</flag>
	<flag>
		<name>contraband</name>
		<value>16</value>
	</flag>
	<flag>
		<name>invis</name>
		<value>32</value>
	</flag>
	<flag>
		<name>force</name>
		<value>64</value>
	</flag>
	<flag>
		<name>nodrop</name>
		<value>128</value>
	</flag>
	<flag>
		<name>bless</name>
		<value>256</value>
	</flag>
	<flag>
		<name>anti_good</name>
		<value>512</value>
	</flag>
	<flag>
		<name>anti_evil</name>
		<value>1024</value>
	</flag>
	<flag>
		<name>anti_neutral</name>
		<value>2048</value>
	</flag>
	<flag>
		<name>noremove</name>
		<value>4096</value>
	</flag>
	<flag>
		<name>inventory</name>
		<value>8192</value>
	</flag>
	<flag>
		<name>anti_soldier</name>
		<value>16384</value>
	</flag>
	<flag>
		<name>anti_thief</name>
		<value>32768</value>
	</flag>
	<flag>
		<name>anti_hunter</name>
		<value>65536</value>
	</flag>
	<flag>
		<name>anti_jedi</name>
		<value>131072</value>
	</flag>
	<flag>
		<name>small_size</name>
		<value>262144</value>
	</flag>
	<flag>
		<name>large_size</name>
		<value>524288</value>
	</flag>
	<flag>
		<name>donation</name>
		<value>1048576</value>
	</flag>
	<flag>
		<name>clan_object</name>
		<value>2097152</value>
	</flag>
	<flag>
		<name>anti_citizen</name>
		<value>4194304</value>
	</flag>
	<flag>
		<name>anti_sith</name>
		<value>8388608</value>
	</flag>
	<flag>
		<name>anti_pilot</name>
		<value>16777216</value>
	</flag>
	<flag>
		<name>hidden</name>
		<value>33554432</value>
	</flag>
	<flag>
		<name>poisoned</name>
		<value>67108864</value>
	</flag>
	<flag>
		<name>covering</name>
		<value>134217728</value>
	</flag>
	<flag>
		<name>personal</name>
		<value>268435456</value>
	</flag>
	<flag>
		<name>burried</name>
		<value>536870912</value>
	</flag>
	<flag>
		<name>prototype</name>
		<value>1073741824</value>
	</flag>
	<flag>
		<name>human_size</name>
		<value>2147483648</value>
	</flag>
</flags>

=== swmud-net/swaedit/data/mobileaffectedflags.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<flags xmlns="http://swmud.pl/ns/swaedit/flags"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/flags src/flags.xsd ">
	<flag>
	    <name>blind</name>
	    <value>1</value>
	</flag>
	<flag>
	    <name>invisible</name>
	    <value>2</value>
	</flag>
	<flag>
	    <name>detect_evil</name>
	    <value>4</value>
	</flag>
	<flag>
	    <name>detect_invis</name>
	    <value>8</value>
	</flag>
	<flag>
	    <name>detect_force</name>
	    <value>16</value>
	</flag>
	<flag>
	    <name>detect_hidden</name>
	    <value>32</value>
	</flag>
	<flag>
	    <name>weaken</name>
	    <value>64</value>
	</flag>
	<flag>
	    <name>sanctuary</name>
	    <value>128</value>
	</flag>
	<flag>
	    <name>faerie_fire</name>
	    <value>256</value>
	</flag>
	<flag>
	    <name>infrared</name>
	    <value>512</value>
	</flag>
	<flag>
	    <name>curse</name>
	    <value>1024</value>
	</flag>
	<flag>
	    <name>dominated</name>
	    <value>2048</value>
	</flag>
	<flag>
	    <name>poison</name>
	    <value>4096</value>
	</flag>
	<flag>
	    <name>protect</name>
	    <value>8192</value>
	</flag>
	<flag>
	    <name>paralysis</name>
	    <value>16384</value>
	</flag>
	<flag>
	    <name>sneak</name>
	    <value>32768</value>
	</flag>
	<flag>
	    <name>hide</name>
	    <value>65536</value>
	</flag>
	<flag>
	    <name>sleep</name>
	    <value>131072</value>
	</flag>
	<flag>
	    <name>charm</name>
	    <value>262144</value>
	</flag>
	<flag>
	    <name>flying</name>
	    <value>524288</value>
	</flag>
	<flag>
	    <name>pass_door</name>
	    <value>1048576</value>
	</flag>
	<flag>
	    <name>floating</name>
	    <value>2097152</value>
	</flag>
	<flag>
	    <name>truesight</name>
	    <value>4194304</value>
	</flag>
	<flag>
	    <name>detecttraps</name>
	    <value>8388608</value>
	</flag>
	<flag>
	    <name>scrying</name>
	    <value>16777216</value>
	</flag>
	<flag>
	    <name>forceinvis</name>
	    <value>33554432</value>
	</flag>
	<flag>
	    <name>shockshield</name>
	    <value>67108864</value>
	</flag>
	<flag>
	    <name>disguise</name>
	    <value>134217728</value>
	</flag>
	<flag>
	    <name>iceshield</name>
	    <value>268435456</value>
	</flag>
	<flag>
	    <name>possess</name>
	    <value>536870912</value>
	</flag>
	<flag>
	    <name>berserk</name>
	    <value>1073741824</value>
	</flag>
	<flag>
	    <name>aqua_breath</name>
	    <value>2147483648</value>
	</flag>
</flags>
