=== swmud-net/swaedit/schemas/highlighter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://swmud.pl/ns/swaedit/highlighter"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://swmud.pl/ns/swaedit/highlighter"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="1.0">

	<xsd:annotation>
		<xsd:appinfo>
			<jxb:globalBindings collectionType="java.util.LinkedList" />
		</xsd:appinfo>
	</xsd:annotation>

	<xsd:element name="highlighter" type="highlighter"></xsd:element>

	<xsd:complexType name="highlighter">
		<xsd:sequence maxOccurs="unbounded" minOccurs="1">
			<xsd:element name="words" type="words"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="words">
		<xsd:sequence maxOccurs="unbounded" minOccurs="1">
			<xsd:element name="word" type="xsd:normalizedString"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="color" type="color" use="optional"
			default="0">
		</xsd:attribute>
		<xsd:attribute name="type" type="type" use="required"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:simpleType name="color">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:pattern value="(0x[A-Fa-f0-9]+)|0"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="type">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="flowInstruction"></xsd:enumeration>
			<xsd:enumeration value="progCommand"></xsd:enumeration>
			<xsd:enumeration value="ifCheck"></xsd:enumeration>
			<xsd:enumeration value="variable"></xsd:enumeration>
			<xsd:enumeration value="ratmVariable"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== swmud-net/swaedit/data/highlighter.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<highlighter xmlns="http://swmud.pl/ns/swaedit/highlighter"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/highlighter src/highlighter.xsd ">

	<words type="flowInstruction" color="0x8B008B">
		<word>if</word>
		<word>else</word>
		<word>endif</word>
		<word>break</word>
		<word>or</word>
	</words>
	<words type="progCommand" color="0x006400">
		<word>mp_close_passage</word>
		<word>mp_damage</word>
		<word>mp_restore</word>
		<word>mp_open_passage</word>
		<word>mp_practice</word>
		<word>mp_slay</word>
		<word>mpaddtolist</word>
		<word>mpremfromlist</word>
		<word>mpaddtowanted</word>
		<word>mpremfromwanted</word>
		<word>mpclrnameslist</word>
		<word>mpadvance</word>
		<word>mpasound</word>
		<word>mpat</word>
		<word>mpdelay</word>
		<word>mpdream</word>
		<word>mp_deposit</word>
		<word>mp_withdraw</word>
		<word>mpecho</word>
		<word>mpechoaround</word>
		<word>mpechoat</word>
		<word>mpforce</word>
		<word>mpinduct</word>
		<word>mpoutcast</word>
		<word>mpinvis</word>
		<word>mpgoto</word>
		<word>mpjunk</word>
		<word>mpkill</word>
		<word>mpmload</word>
		<word>mpmset</word>
		<word>mpnoecho</word>
		<word>mpnothing</word>
		<word>mpoload</word>
		<word>mposet</word>
		<word>mppurge</word>
		<word>mpstat</word>
		<word>mpsuggest</word>
		<word>mpresetroom</word>
		<word>mpstun</word>
		<word>mptransfer</word>
		<word>mpapply</word>
		<word>mpapplyb</word>
		<word>mpgain</word>
		<word>mpqmload</word>
		<word>mpqoload</word>
	</words>
	<words type="ifCheck" color="0x00008B">
		<word>rand</word>
		<word>economy</word>
		<word>mobinroom</word>
		<word>timeskilled</word>
		<word>ovnumhere</word>
		<word>onamehere</word>
		<word>otypehere</word>
		<word>ovnumroom</word>
		<word>onameroom</word>
		<word>otyperoom</word>
		<word>ovnumcarry</word>
		<word>onamecarry</word>
		<word>otypecarry</word>
		<word>ovnumwear</word>
		<word>onamewear</word>
		<word>otypewear</word>
		<word>ovnuminv</word>
		<word>onameinv</word>
		<word>otypeinv</word>
		<word>weapontypeinv</word>
		<word>weapontypewear</word>
		<word>weapontypecarry</word>
		<word>questdone</word>
		<word>cansee</word>
		<word>iswanted</word>
		<word>ovnuminvchar</word>
		<word>onameinvchar</word>
		<word>otypeinvchar</word>
		<word>ovnumwearchar</word>
		<word>onamewearchar</word>
		<word>otypewearchar</word>
		<word>otypecarrychar</word>
		<word>ovnumcarrychar</word>
		<word>onamecarrychar</word>
		<word>ismobinvis</word>
		<word>mobinvislevel</word>
		<word>ispc</word>
		<word>isstunned</word>
		<word>isnpc</word>
		<word>ismounted</word>
		<word>isgood</word>
		<word>isneutral</word>
		<word>isevil</word>
		<word>isfight</word>
		<word>isimmort</word>
		<word>ischarmed</word>
		<word>isinnameslist</word>
		<word>nameslistfull</word>
		<word>nameslistempty</word>
		<word>isfollow</word>
		<word>isaffected</word>
		<word>hitprcnt</word>
		<word>inroom</word>
		<word>wasinroom</word>
		<word>sex</word>
		<word>position</word>
		<word>questid</word>
		<word>questp</word>
		<word>questpoints</word>
		<word>ishelled</word>
		<word>level</word>
		<word>credits</word>
		<word>race</word>
		<word>class</word>
		<word>clan</word>
		<word>iscouncil</word>
		<word>clantype</word>
		<word>str</word>
		<word>wis</word>
		<word>int</word>
		<word>dex</word>
		<word>con</word>
		<word>cha</word>
		<word>frc</word>
		<word>lck</word>
		<word>objtype</word>
		<word>objval0</word>
		<word>objval1</word>
		<word>objval2</word>
		<word>objval3</word>
		<word>objval4</word>
		<word>objval5</word>
		<word>objiswear</word>
		<word>number</word>
		<word>name</word>
		<word>var</word>
		<word>isset</word>
		<word>isnumber</word>
	</words>
	<words type="variable" color="0xFF8C00">
		<word>i</word>
		<word>n</word>
		<word>t</word>
		<word>r</word>
		<word>o</word>
		<word>p</word>
	</words>
	<words type="ratmVariable" color="0x66CDAA">
		<word>vl0</word>
		<word>vl1</word>
		<word>vl2</word>
		<word>vl3</word>
		<word>vl4</word>
		<word>vl5</word>
		<word>vl6</word>
		<word>vl7</word>
		<word>vl8</word>
		<word>vl9</word>
	</words>
	<words type="ratmVariable" color="0x008B8B">
		<word>vg0</word>
		<word>vg1</word>
		<word>vg2</word>
		<word>vg3</word>
		<word>vg4</word>
		<word>vg5</word>
		<word>vg6</word>
		<word>vg7</word>
		<word>vg8</word>
		<word>vg9</word>
	</words>
</highlighter>
