=== swmud-net/swaedit/schemas/itemtypes.xsd
<?xml version="1.0" encoding="ISO-8859-2"?>
<xsd:schema targetNamespace="http://swmud.pl/ns/swaedit/itemtypes"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://swmud.pl/ns/swaedit/itemtypes"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="1.0">

	<xsd:annotation>
		<xsd:appinfo>
			<jxb:globalBindings collectionType="java.util.LinkedList" />
		</xsd:appinfo>
	</xsd:annotation>

	<xsd:element name="itemtypes" type="itemtypes"></xsd:element>

	<xsd:complexType name="itemtypes">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="itemtype" type="itemtype"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="itemtype">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="value" type="xsd:int"></xsd:element>
			<xsd:element name="values" type="values"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="visible" type="xsd:boolean" use="optional"
			default="true">
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="value">
		<xsd:sequence>
			<xsd:element name="no" type="xsd:short"></xsd:element>
			<xsd:element name="name" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="subvalues" type="subvalues"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="values">
		<xsd:sequence maxOccurs="6" minOccurs="0">
			<xsd:element name="value" type="value"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="subvalues">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="subvalue" type="subvalue"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="type" use="optional" default="auto">
			<xsd:simpleType>
				<xsd:restriction base="xsd:normalizedString">
					<xsd:enumeration value="auto"></xsd:enumeration>
					<xsd:enumeration value="value"></xsd:enumeration>
					<xsd:enumeration value="flags"></xsd:enumeration>
					<xsd:enumeration value="types"></xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="subvalue">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="value" type="xsd:normalizedString"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="constraint" use="optional"
			default="none">
			<xsd:simpleType>
				<xsd:restriction base="xsd:normalizedString">
					<xsd:enumeration value="none"></xsd:enumeration>
					<xsd:enumeration value="spell"></xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>


</xsd:schema>

=== swmud-net/swaedit/data/itemtypes.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<itemtypes xmlns="http://swmud.pl/ns/swaedit/itemtypes"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/itemtypes src/itemtypes.xsd ">


	<itemtype>
		<name>none</name>
		<value>0</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>light</name>
		<value>1</value>
		<values>
			<value>
				<no>2</no>
				<name>light</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>weapon</name>
		<value>5</value>
		<values>
			<value>
				<no>0</no>
				<name>condition</name>
				<subvalues/>
			</value>
			<value>
				<no>1</no>
				<name>min damage</name>
				<subvalues/>
			</value>
			<value>
				<no>2</no>
				<name>max damage</name>
				<subvalues/>
			</value>
			<value>
				<no>3</no>
				<name>weapon type</name>
				<subvalues>
					<subvalue>
						<name>none</name>
						<value>0</value>
					</subvalue>
					<subvalue>
						<name>vibro axe</name>
						<value>1</value>
					</subvalue>
					<subvalue>
						<name>vibro blade</name>
						<value>2</value>
					</subvalue>
					<subvalue>
						<name>lightsaber</name>
						<value>3</value>
					</subvalue>
					<subvalue>
						<name>whip</name>
						<value>4</value>
					</subvalue>
					<subvalue>
						<name>claw</name>
						<value>5</value>
					</subvalue>
					<subvalue>
						<name>blaster</name>
						<value>6</value>
					</subvalue>
					<subvalue>
						<name>bludgeon</name>
						<value>8</value>
					</subvalue>
					<subvalue>
						<name>bowcaster</name>
						<value>9</value>
					</subvalue>
					<subvalue>
						<name>force pike</name>
						<value>11</value>
					</subvalue>
				</subvalues>
			</value>
			<value>
				<no>4</no>
				<name>charges</name>
				<subvalues/>
			</value>
			<value>
				<no>5</no>
				<name>max charges</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>


	<itemtype>
		<name>treasure</name>
		<value>8</value>
		<values/>
	</itemtype>



	<itemtype>
		<name>armor</name>
		<value>9</value>
		<values>
			<value>
				<no>0</no>
				<name>condition</name>
				<subvalues/>
			</value>
			<value>
				<no>1</no>
				<name>ac</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>potion</name>
		<value>10</value>
		<values>
			<value>
				<no>0</no>
				<name>slevel</name>
				<subvalues/>
			</value>
			<value>
				<no>1</no>
				<name>spell1</name>
				<subvalues/>
			</value>
			<value>
				<no>2</no>
				<name>spell2</name>
				<subvalues/>
			</value>
			<value>
				<no>3</no>
				<name>spell3</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>computer</name>
		<value>11</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>trash</name>
		<value>13</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>container</name>
		<value>15</value>
		<values>
			<value>
				<no>0</no>
				<name>capacity</name>
				<subvalues/>
			</value>
			<value>
				<no>1</no>
				<name>container flags</name>
				<subvalues type="flags">
					<subvalue>
						<name>closeable</name>
						<value>1</value>
					</subvalue>
					<subvalue>
						<name>pickproof</name>
						<value>2</value>
					</subvalue>
					<subvalue>
						<name>closed</name>
						<value>4</value>
					</subvalue>
					<subvalue>
						<name>locked</name>
						<value>8</value>
					</subvalue>
				</subvalues>
			</value>
			<value>
				<no>2</no>
				<name>key</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>drink container</name>
		<value>17</value>
		<values>
			<value>
				<no>0</no>
				<name>liquid total</name>
				<subvalues/>
			</value>
			<value>
				<no>1</no>
				<name>liquid left</name>
				<subvalues/>
			</value>
			<value>
				<no>2</no>
				<name>liquid type</name>
				<subvalues>
					<subvalue>
						<name>water</name>
						<value>0</value>
					</subvalue>
					<subvalue>
						<name>beer</name>
						<value>1</value>
					</subvalue>
					<subvalue>
						<name>wine</name>
						<value>2</value>
					</subvalue>
					<subvalue>
						<name>ale</name>
						<value>3</value>
					</subvalue>
					<subvalue>
						<name>dark-ale</name>
						<value>4</value>
					</subvalue>
					<subvalue>
						<name>whisky</name>
						<value>5</value>
					</subvalue>
					<subvalue>
						<name>lemonade</name>
						<value>6</value>
					</subvalue>
					<subvalue>
						<name>firebreather</name>
						<value>7</value>
					</subvalue>
					<subvalue>
						<name>local-speciality</name>
						<value>8</value>
					</subvalue>
					<subvalue>
						<name>slime-mold-juice</name>
						<value>9</value>
					</subvalue>
					<subvalue>
						<name>milk</name>
						<value>10</value>
					</subvalue>
					<subvalue>
						<name>tea</name>
						<value>11</value>
					</subvalue>
					<subvalue>
						<name>coffe</name>
						<value>12</value>
					</subvalue>
					<subvalue>
						<name>blood</name>
						<value>13</value>
					</subvalue>
					<subvalue>
						<name>salt-water</name>
						<value>14</value>
					</subvalue>
					<subvalue>
						<name>cola</name>
						<value>15</value>
					</subvalue>
					<subvalue>
						<name>ponch</name>
						<value>16</value>
					</subvalue>
					<subvalue>
						<name>grog</name>
						<value>17</value>
					</subvalue>
					<subvalue>
						<name>shake</name>
						<value>18</value>
					</subvalue>
					<subvalue>
						<name>drink</name>
						<value>19</value>
					</subvalue>
				</subvalues>
			</value>
			<value>
				<no>3</no>
				<name>poisoned</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>key</name>
		<value>18</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>food</name>
		<value>19</value>
		<values>
			<value>
				<no>0</no>
				<name>food hours</name>
				<subvalues/>
			</value>
			<value>
				<no>3</no>
				<name>poisoned</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>money</name>
		<value>20</value>
		<values>
			<value>
				<no>0</no>
				<name>credits</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>corpse NPC</name>
		<value>23</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>corpse PC</name>
		<value>24</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>fountain</name>
		<value>25</value>
		<values>
			<value>
				<no>0</no>
				<name>liquid total</name>
				<subvalues/>
			</value>
			<value>
				<no>1</no>
				<name>liquid left</name>
				<subvalues/>
			</value>
			<value>
				<no>2</no>
				<name>liquid type</name>
				<subvalues>
					<subvalue>
						<name>water</name>
						<value>0</value>
					</subvalue>
					<subvalue>
						<name>beer</name>
						<value>1</value>
					</subvalue>
					<subvalue>
						<name>wine</name>
						<value>2</value>
					</subvalue>
					<subvalue>
						<name>ale</name>
						<value>3</value>
					</subvalue>
					<subvalue>
						<name>dark-ale</name>
						<value>4</value>
					</subvalue>
					<subvalue>
						<name>whisky</name>
						<value>5</value>
					</subvalue>
					<subvalue>
						<name>lemonade</name>
						<value>6</value>
					</subvalue>
					<subvalue>
						<name>firebreather</name>
						<value>7</value>
					</subvalue>
					<subvalue>
						<name>local-speciality</name>
						<value>8</value>
					</subvalue>
					<subvalue>
						<name>slime-mold-juice</name>
						<value>9</value>
					</subvalue>
					<subvalue>
						<name>milk</name>
						<value>10</value>
					</subvalue>
					<subvalue>
						<name>tea</name>
						<value>11</value>
					</subvalue>
					<subvalue>
						<name>coffe</name>
						<value>12</value>
					</subvalue>
					<subvalue>
						<name>blood</name>
						<value>13</value>
					</subvalue>
					<subvalue>
						<name>salt-water</name>
						<value>14</value>
					</subvalue>
					<subvalue>
						<name>cola</name>
						<value>15</value>
					</subvalue>
					<subvalue>
						<name>ponch</name>
						<value>16</value>
					</subvalue>
					<subvalue>
						<name>grog</name>
						<value>17</value>
					</subvalue>
					<subvalue>
						<name>shake</name>
						<value>18</value>
					</subvalue>
					<subvalue>
						<name>drink</name>
						<value>19</value>
					</subvalue>
				</subvalues>
			</value>
			<value>
				<no>3</no>
				<name>poisoned</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>key</name>
		<value>18</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>pill</name>
		<value>26</value>
		<values>
			<value>
				<no>0</no>
				<name>slevel</name>
				<subvalues/>
			</value>
			<value>
				<no>1</no>
				<name>spell1</name>
				<subvalues/>
			</value>
			<value>
				<no>2</no>
				<name>spell2</name>
				<subvalues/>
			</value>
			<value>
				<no>3</no>
				<name>spell3</name>
				<subvalues/>
			</value>
		</values>
	</itemtype>




	<itemtype>
		<name>scraps</name>
		<value>29</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>pipe</name>
		<value>30</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>herb container</name>
		<value>31</value>
		<values/>
	</itemtype>




	<itemtype>
		<name>herb</name>
		<value>32</value>
		<values/>
	</itemtype>


	<itemtype>
		<name>switch</name>
		<value>36</value>
		<values>
			<value>
				<no>0</no>
				<name>tflags</name>
				<subvalues type="flags">
					<subvalue>
						<name>closeable</name>
						<value>1</value>
					</subvalue>
					<subvalue>
						<name>pickproof</name>
						<value>2</value>
					</subvalue>
					<subvalue>
						<name>closed</name>
						<value>4</value>
					</subvalue>
					<subvalue>
						<name>locked</name>
						<value>8</value>
					</subvalue>
				</subvalues>
			</value>
		</values>
	</itemtype>



	<itemtype>
		<name>lever</name>
		<value>37</value>
		<values>
			<value>
				<no>0</no>
				<name>tflags</name>
				<subvalues type="flags">
					<subvalue>
						<name>closeable</name>
