=== swmud-net/swaedit/schemas/names.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://swmud.pl/ns/swaedit/names"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://swmud.pl/ns/swaedit/names"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="1.0">

	<xsd:annotation>
		<xsd:appinfo>
			<jxb:globalBindings collectionType="java.util.LinkedList"/>
		</xsd:appinfo>
	</xsd:annotation>

	<xsd:element name="names" type="names"></xsd:element>

	<xsd:complexType name="names">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="name" type="xsd:normalizedString"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== swmud-net/swaedit/data/mobilespecfunctions.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<names xmlns="http://swmud.pl/ns/swaedit/names"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/names src/names.xsd ">
	<name>spec_auth</name>
	<name>spec_cast_adept</name>
	<name>spec_clan_guard</name>
	<name>spec_customs_alcohol</name>
	<name>spec_customs_smut</name>
	<name>spec_customs_spice</name>
	<name>spec_customs_weapons</name>
	<name>spec_dark_jedi</name>
	<name>spec_executioner</name>
	<name>spec_fido</name>
	<name>spec_guard</name>
	<name>spec_guardian</name>
	<name>spec_janitor</name>
	<name>spec_jedi</name>
	<name>spec_mayor</name>
	<name>spec_newbie_pilot</name>
	<name>spec_new_republic_trooper</name>
	<name>spec_poison</name>
	<name>spec_police</name>
	<name>spec_police_attack</name>
	<name>spec_police_fine</name>
	<name>spec_police_jail</name>
	<name>spec_prosecutor</name>
	<name>spec_stormtrooper</name>
	<name>spec_thief</name>
</names>

=== swmud-net/swaedit/data/planets.xml
<?xml version="1.0" encoding="UTF-8"?>
<names xmlns="http://swmud.pl/ns/swaedit/names"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/names src/names.xsd ">
	<name>Adari</name>
	<name>Anoth</name>
	<name>Bakura</name>
	<name>Bespin</name>
	<name>Biosh</name>
	<name>Byss</name>
	<name>Corellia</name>
	<name>Coruscant</name>
	<name>Dagobah</name>
	<name>Endor</name>
	<name>Gamorr</name>
	<name>Geonosis</name>
	<name>Hapes</name>
	<name>Honoghr</name>
	<name>Hoth</name>
	<name>Jhas</name>
	<name>Kamino</name>
	<name>Kashyyyk</name>
	<name>Kessel</name>
	<name>Korriban</name>
	<name>Kuat</name>
	<name>Mon Calamari</name>
	<name>Naboo</name>
	<name>Nar Shadda</name>
	<name>Nushk</name>
	<name>Ordaj</name>
	<name>Ord Mantell</name>
	<name>Ryloth</name>
	<name>Selonia</name>
	<name>Shron</name>
	<name>Tatooine</name>
	<name>Umgul</name>
	<name>Wayland</name>
	<name>Yavin IV</name>
</names>

=== swmud-net/swaedit/data/races.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<names xmlns="http://swmud.pl/ns/swaedit/names"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/names src/names.xsd ">
	<name>Human</name>
	<name>Adarian</name>
	<name>Animal</name>
	<name>Aqualish</name>
	<name>Arcona</name>
	<name>Arkanianin</name>
	<name>Barabel</name>
	<name>Bimm</name>
	<name>Bith</name>
	<name>Bothan</name>
	<name>Caridanin</name>
	<name>Cerean</name>
	<name>Chadra-Fan</name>
	<name>Chubbit</name>
	<name>Codru Ji</name>
	<name>Coway</name>
	<name>Deavaronian</name>
	<name>Defel</name>
	<name>Drall</name>
	<name>Droll</name>
	<name>Drovianin</name>
	<name>Duch Lorda Sith</name>
	<name>Duch Mistrza Jedi</name>
	<name>Duinuogwuin</name>
	<name>Duros</name>
	<name>Etti</name>
	<name>Ewok</name>
	<name>Fia</name>
	<name>Firrerreonianin</name>
	<name>Gados</name>
	<name>Gamorrean</name>
	<name>Gops</name>
	<name>Gorax</name>
	<name>Gotal</name>
	<name>Gran</name>
	<name>Gungan</name>
	<name>H'drach</name>
	<name>Hutt</name>
	<name>Iktotchi</name>
	<name>Insect</name>
	<name>Ithorian</name>
	<name>Ixel</name>
	<name>Jawa</name>
	<name>Kel Dor</name>
	<name>Khommowin</name>
	<name>Kurtzen</name>
	<name>Massassi</name>
	<name>Meeki</name>
	<name>Melodianin</name>
	<name>Mon Calamari</name>
	<name>Moocher</name>
	<name>Mrlss</name>
	<name>Mulk</name>
	<name>Myneyrsh</name>
	<name>Net</name>
	<name>Noghri</name>
	<name>Object</name>
	<name>Plant</name>
	<name>Pływak</name>
	<name>Psadan</name>
	<name>P'W'eck</name>
	<name>Pydyrian</name>
	<name>Quarren</name>
	<name>Rodian</name>
	<name>Selonianin</name>
	<name>Ssi-ruuk</name>
	<name>Sullustan</name>
	<name>Talz</name>
	<name>Tchuukthai</name>
	<name>Teek</name>
	<name>T'landa Til</name>
	<name>Toka</name>
	<name>Trandoshan</name>
	<name>Tusken</name>
	<name>Twi'lek</name>
	<name>Tynnanin</name>
	<name>Ughnaught</name>
	<name>Verpine</name>
	<name>Vors</name>
	<name>Vratix</name>
	<name>Wookiee</name>
	<name>Wyrwulf</name>
	<name>Yaka</name>
	<name>Yaveth</name>
	<name>Ysanna</name>
	<name>Yuuzhan Vong</name>
	<name>Yuzzum</name>
	<name>Zabrak</name>
	<name>Zieleniak</name>
</names>

=== swmud-net/swaedit/data/languages.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<names xmlns="http://swmud.pl/ns/swaedit/names"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/names src/names.xsd ">
	<name>Basic</name>
	<name>Adariański</name>
	<name>Aqualishański</name>
	<name>Arcoński</name>
	<name>Barabelski</name>
	<name>Bithański</name>
	<name>Bothański</name>
	<name>Cereański</name>
	<name>Chadra-fański</name>
	<name>Devaroński</name>
	<name>Defelski</name>
	<name>Durosjański</name>
	<name>Gamorreański</name>
	<name>Antariański</name>
	<name>Grański</name>
	<name>Huttyjski</name>
	<name>Iktotchiański</name>
	<name>Ithoriański</name>
	<name>Kel Doriański</name>
	<name>Mon Calamariański</name>
	<name>Honoghrański</name>
	<name>Quarreński</name>
	<name>Rodiański</name>
	<name>Sullustiański</name>
	<name>Dosh</name>
	<name>Ryliański</name>
	<name>Verpiński</name>
	<name>Shyriiwook</name>
	<name>Lekku</name>
	<name>Verpidio</name>
	<name>Binarny</name>
	<name>Gungański</name>
	<name>Jawów</name>
	<name>Ewoków</name>
	<name>Mando'a</name>
	<name>Olys Corellisi</name>
</names>

=== swmud-net/swaedit/data/progtypes.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<names xmlns="http://swmud.pl/ns/swaedit/names"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/names src/names.xsd ">
	<name>in_file_prog</name>
	<name>act_prog</name>
	<name>speech_prog</name>
	<name>rand_prog</name>
	<name>fight_prog</name>
	<name>rfight_prog</name>
	<name>death_prog</name>
	<name>rdeath_prog</name>
	<name>hitprcnt_prog</name>
	<name>entry_prog</name>
	<name>enter_prog</name>
	<name>greet_prog</name>
	<name>rgreet_prog</name>
	<name>ogreet_prog</name>
	<name>all_greet_prog</name>
	<name>give_prog</name>
	<name>bribe_prog</name>
	<name>hour_prog</name>
	<name>time_prog</name>
	<name>wear_prog</name>
	<name>remove_prog</name>
	<name>sac_prog</name>
	<name>tell_prog</name>
	<name>exa_prog</name>
	<name>zap_prog</name>
	<name>get_prog</name>
	<name>drop_prog</name>
	<name>damage_prog</name>
	<name>repair_prog</name>
	<name>quest_prog</name>
	<name>speechiw_prog</name>
	<name>pull_prog</name>
	<name>push_prog</name>
	<name>sleep_prog</name>
	<name>rest_prog</name>
	<name>leave_prog</name>
	<name>script_prog</name>
	<name>use_prog</name>
	<name>dialog_prog</name>
</names>
