=== swmud-net/swaedit/schemas/types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://swmud.pl/ns/swaedit/types"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://swmud.pl/ns/swaedit/types"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="1.0">

	<xsd:annotation>
		<xsd:appinfo>
			<jxb:globalBindings collectionType="java.util.LinkedList"/>
		</xsd:appinfo>
	</xsd:annotation>

	<xsd:element name="types" type="types"></xsd:element>

	<xsd:complexType name="types">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="type" type="type"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="type">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="value" type="xsd:int"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== swmud-net/swaedit/data/roomsectortypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<types xmlns="http://swmud.pl/ns/swaedit/types"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/types src/types.xsd ">
	<type>
		<name>inside</name>
		<value>0</value>
	</type>
	<type>
		<name>city</name>
		<value>1</value>
	</type>
	<type>
		<name>field</name>
		<value>2</value>
	</type>
	<type>
		<name>forest</name>
		<value>3</value>
	</type>
	<type>
		<name>hills</name>
		<value>4</value>
	</type>
	<type>
		<name>mountain</name>
		<value>5</value>
	</type>
	<type>
		<name>water_swim</name>
		<value>6</value>
	</type>
	<type>
		<name>water_noswim</name>
		<value>7</value>
	</type>
	<type>
		<name>underwater</name>
		<value>8</value>
	</type>
	<type>
		<name>air</name>
		<value>9</value>
	</type>
	<type>
		<name>desert</name>
		<value>10</value>
	</type>
	<type>
		<name>dunno</name>
		<value>11</value>
	</type>
	<type>
		<name>oceanfloor</name>
		<value>12</value>
	</type>
	<type>
		<name>underground</name>
		<value>13</value>
	</type>
	<type>
		<name>jail_corridor</name>
		<value>14</value>
	</type>
	<type>
		<name>jail_office</name>
		<value>15</value>
	</type>
	<type>
		<name>jail_cell</name>
		<value>16</value>
	</type>
	<type>
		<name>jail_entrance</name>
		<value>17</value>
	</type>
</types>

=== swmud-net/swaedit/data/positions.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<types xmlns="http://swmud.pl/ns/swaedit/types"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://swmud.pl/ns/swaedit/types src/types.xsd ">
	<type>
		<name>dead</name>
		<value>0</value>
	</type>
	<type>
		<name>mortal</name>
		<value>1</value>
	</type>
	<type>
		<name>incap</name>
		<value>2</value>
	</type>
	<type>
		<name>stunned</name>
		<value>3</value>
	</type>
	<type>
		<name>sleeping</name>
		<value>4</value>
	</type>
	<type>
		<name>resting</name>
		<value>5</value>
	</type>
	<type>
		<name>sitting</name>
		<value>6</value>
	</type>
	<type>
		<name>fighting</name>
		<value>7</value>
	</type>
	<type>
		<name>standing</name>
		<value>8</value>
	</type>
	<type>
		<name>mounted</name>
		<value>9</value>
	</type>
	<type>
		<name>shove</name>
		<value>10</value>
	</type>
	<type>
		<name>drag</name>
		<value>11</value>
	</type>
</types>
